### ISSUE TITLE
error on torchspigot

### ISSUE THREAD

**Issue by ghost** [InventivetalentDev/MapManager#11]
ss
![2017-05-01_14 16 33](https://cloud.githubusercontent.com/assets/5884000/25579512/dbc0d24c-2e78-11e7-8144-d89e02647290.png)

logs
```
[14:14:08] [Server thread/INFO]: QiiQii issued server command: /afremove one
[14:14:11] [Server thread/INFO]: QiiQii issued server command: /afcreate one https://media.giphy.com/media/jG186kNLKs6TS/giphy.gif
[14:14:14] [pool-11-thread-1/INFO]: [AnimatedFrames] Downloaded 'https://media.giphy.com/media/jG186kNLKs6TS/giphy.gif' to 'plugins\AnimatedFrames\images\aHR0cHM6Ly9tZWRpYS5naXBoeS5jb20vbWVkaWEvakcxODZrTkxLczZUUy9naXBoeS5naWY='.
[14:14:14] [pool-11-thread-1/INFO]: [AnimatedFrames] Animation length for 'one' is zero. Creating non-animated image.
[14:14:14] [pool-11-thread-1/WARN]: Exception in thread "pool-11-thread-1" 
[14:14:14] [pool-11-thread-1/WARN]: java.lang.NullPointerException
[14:14:14] [pool-11-thread-1/WARN]: 	at org.inventivetalent.animatedframes.AnimatedFrame.scaleImage(AnimatedFrame.java:240)
[14:14:14] [pool-11-thread-1/WARN]: 	at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:137)
[14:14:14] [pool-11-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:14:14] [pool-11-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:14:14] [pool-11-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

timings
https://timings.aikar.co/?id=4e97a3f9a4d3405b81298fc0e18f4c67

config
```
# If vanilla maps should be allowed to be sent to the players (less efficient, since we need to check the id of every sent map)
allowVanilla: true

# If the plugin checks for duplicate images before creating a new one (Less efficient when first creating a image, but more efficient overall)
checkDuplicates: true

# Cache the packet data in the image object (less CPU intensive for a lot of players, but probably a bit more memory intensive depending on the image size)
cacheData: true

sender:
  # Delay between map packets (ticks)
  delay: 2

  # Maximum amount of map packets sent at once
  amount: 10

  # Allow immediate sending of map data
  allowQueueBypass: true

# Enable this if you are using PaperSpigot (and/or you get this error: http://paste.inventivetalent.org/damuhonebu)
paperSpigot: true
```

torchspigot
https://github.com/TorchSpigot/Torch

build 115
https://115-61716775-gh.circle-artifacts.com/0/tmp/circle-artifacts.mzB8ew0/Torchpowered-1.11.2.jar

**Comment by InventivetalentDev** [comment]
> ## What plugins ae < --- ( use: are ) you using? *Type /plugins* 

Or maybe just answer the question, if you're already smart enough to correct it? No?

**Comment by mat41997** [comment]
i don't know
I do not know English
I do not understand what you write
