### ISSUE TITLE
Error occurs and spams console in Spigot 1.12

### ISSUE THREAD

**Issue by robotnikthingy** [InventivetalentDev/MapManager#14]
## What steps will reproduce the problem?  
1.  Load pplugin on server running Spigot 1.12
2.  Server gets spammed with error from plugin

## What were you expecting to happen? What happened instead?  
Console would not get spammed with error and plugin would work with 1.12

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.3.4-SNAPSHOT
## What Spigot version are you using? *Type /version*  
1.12
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
`[12:50:01] [Craft Scheduler Thread - 114/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.PacketPlayOutMap.<init>(int, [B)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at java.lang.Class.getConstructor0(Class.java:3082)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at java.lang.Class.getConstructor(Class.java:1825)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at org.inventivetalent.mapmanager.MapSender.constructPacket_1_7(MapSender.java:168)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at org.inventivetalent.mapmanager.MapSender.access$100(MapSender.java:19)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at org.inventivetalent.mapmanager.MapSender$2.run(MapSender.java:104)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:50:01] [Craft Scheduler Thread - 114/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)`
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

**Comment by GrangerTheDog** [comment]
Can confirm!
