### ISSUE TITLE
Error occurred while enabling MapManager v1.7.2-SNAPSHOT

### ISSUE THREAD

**Issue by shuiqing2046** [InventivetalentDev/MapManager#25]
`[14:54:41 INFO]: [MapManager] Vanilla Maps are allowed. Trying to discover occupied Map IDs...
[14:54:44 INFO]: [MapManager] Found 1192 occupied IDs.
[14:54:44 ERROR]: Error occurred while enabling MapManager v1.7.2-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: SEM_VER_SNAPSHOT
        at org.inventivetalent.mapmanager.MapManagerPlugin.onEnable(MapManagerPlugin.java:101) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-495]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-495]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-495]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-495]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-495]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[14:54:44 INFO]: [MapManager] Disabling MapManager v1.7.2-SNAPSHOT`

**Comment by shuiqing2046** [comment]
Sorry, I got it wrong. Please close it.
Upgrade PacketListenerAPI_v3.7.2-SNAPSHOT.jar error to solve.
