### ISSUE TITLE
NoSuchFieldError (Resolved at the time of writing issue)

### ISSUE THREAD

**Issue by fax1ty** [InventivetalentDev/MapManager#29]
## What steps will reproduce the problem?  
1. Downlaod JAR
2. Use it in your plugin
3. ~~*Get some troubles*~~ Just don't get anything

## What were you expecting to happen? What happened instead?  
I just wanted to check this API, but it doesn't work

## MapManager Version
1.7.2-SNAPSHOT

## Core version
PaperClip 1.13.2 (530b)

## Plugins 
![image](https://user-images.githubusercontent.com/26363214/53304930-7d4ca100-3894-11e9-975f-84841b9368e7.png)

Put on a clean build...

## Error Log
```[00:04:28 ERROR]: Error occurred while enabling MapManager v1.7.2-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: SEM_VER_SNAPSHOT
        at org.inventivetalent.mapmanager.MapManagerPlugin.onEnable(MapManagerPlugin.java:101) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-530]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-530]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406) ~[patched_1.13.2.jar:git-Paper-530]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-530]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-530]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-530]        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-530]        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-530]        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-530]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-530]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

As I understand it, there is a problem with the plugin [update module](https://github.com/InventivetalentDev/MapManager/blob/a2bc09f0768e5e56aedfe2072225268c3de669aa/src/org/inventivetalent/mapmanager/MapManagerPlugin.java#L101).
I do not know why there was an error about the absence of the field, if it is [defined](https://github.com/InventivetalentDev/SpigetUpdater/blob/8148e8c1d61f9e51017d9173f455bc0345b2a1ec/Core/src/main/java/org/inventivetalent/update/spiget/comparator/VersionComparator.java#L67).

[NoSuchFieldError](https://docs.oracle.com/javase/7/docs/api/java/lang/NoSuchFieldError.html):
```Thrown if an application tries to access or modify a specified field of an object, and that object no longer has that field.
Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.
```
Are there incompatible versions of additional APIs?

Yep! Please, update [this](https://www.spigotmc.org/resources/api-packetlistenerapi.2930/) to the latest version from GitHub.
Because the link in the [main post](https://www.spigotmc.org/resources/api-mapmanager.19198/) leads to an outdated API (3.7.1)

**Comment by Th3Shadowbroker** [comment]
Jep! Building the PacketListenerAPI manually solved it. I were already wondering why the source code contained the "missing" field (I were using 3.7.1 from spigot before.) 👍
