### ISSUE TITLE
Needs updating for 1.16

### ISSUE THREAD

**Issue by OverDhill** [InventivetalentDev/MapManager#60]
## What steps will reproduce the problem?  
1. Loading Paper will give a lot of errors in the log file.  Nothing seems to be broke in the game.   

```
[21:32:46] [Server thread/ERROR]: Error loading saved data: map_1025
java.lang.IllegalArgumentException: Invalid map dimension: 12
at net.minecraft.server.v1_16_R1.WorldMap.lambda$a$0(WorldMap.java:98) ~[patched_1.16.1.jar:git-Paper-18]
at java.util.Optional.orElseGet(Unknown Source) ~[?:1.8.0_251]
at net.minecraft.server.v1_16_R1.WorldMap.a(WorldMap.java:81) ~[patched_1.16.1.jar:git-Paper-18]
at net.minecraft.server.v1_16_R1.WorldPersistentData.c(WorldPersistentData.java:68) ~[patched_1.16.1.jar:git-Paper-18]
at net.minecraft.server.v1_16_R1.WorldPersistentData.b(WorldPersistentData.java:52) ~[patched_1.16.1.jar:git-Paper-18]
at net.minecraft.server.v1_16_R1.WorldServer.a(WorldServer.java:1700) ~[patched_1.16.1.jar:git-Paper-18]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.getMap(CraftServer.java:1452) ~[patched_1.16.1.jar:git-Paper-18]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.getMap(CraftServer.java:231) ~[patched_1.16.1.jar:git-Paper-18]
at org.bukkit.Bukkit.getMap(Bukkit.java:627) ~[patched_1.16.1.jar:git-Paper-18]
at org.inventivetalent.mapmanager.MapManagerPlugin.onEnable(MapManagerPlugin.java:88) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-18]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-18]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-18]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:498) ~[patched_1.16.1.jar:git-Paper-18]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:412) ~[patched_1.16.1.jar:git-Paper-18]
at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-18]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-18]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-18]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-18]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] 
```
2. 
3. 

## What Spigot version are you using? *Type /version*  
Paper 24

**Comment by InventivetalentDev** [comment]
This is likely not specific to 1.16 as the same error occurs when you load maps in deleted dimensions.

**Comment by stijnb1234** [comment]
Take a look at #51
