### ISSUE TITLE
java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by stijnb1234** [InventivetalentDev/MapManager#71]
**Describe the bug**
I get an error when I try to load a map.

**To Reproduce**
1. Load a map.
2. See the error.

**Expected behavior**
It should just work.

**Additional context**
```
[13:15:53 WARN]: [MapManager] Task #2047 for MapManager v1.8.2-SNAPSHOT generated an exception
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
        at org.inventivetalent.mapmanager.MapSender.sendMap(MapSender.java:72) ~[?:?]
        at org.inventivetalent.mapmanager.MapSender$1.run(MapSender.java:58) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-742]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-742]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-742]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-742]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-742]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-742]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-742]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

_(This is an issue since v1.8.2, in v1.8.1 it works fine)_

**Comment by stijnb1234** [comment]
No response.
