### ISSUE TITLE
Latest Map Manager does not work on 1.17

### ISSUE THREAD

**Issue by OBattler** [InventivetalentDev/MapManager#72]
**Describe the bug**
After I updated it and PacketListenerAPI to the latest, the latter now loads fine, but MapManager errors.

**To Reproduce**
Steps to reproduce the behavior: Run the latest MapManager and PacketListenerAPI on Paper 1.17.

**Expected behavior**
I expected it to load without issues.

**Screenshots**
None.

**Additional context**
Stack trace of the error:
```
[17:23:43] [Server thread/INFO]: [MapManager] Enabling MapManager v1.8.3-SNAPSHOT
--
[17:23:43]  [Server thread/INFO]: [ReflectionHelper/MinecraftVersion] I am loaded  from package org.inventivetalent.reflection.minecraft
[17:23:43] [Server thread/INFO]: [ReflectionHelper/MinecraftVersion] Version is v1_17_R1 (11701)
[17:23:43] [Server thread/ERROR]: Error occurred while enabling MapManager v1.8.3-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
at org.inventivetalent.mapmanager.MapManagerPlugin.onEnable(MapManagerPlugin.java:70) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: class cannot be null
at org.inventivetalent.reflection.resolver.MemberResolver.<init>(MemberResolver.java:20) ~[?:?]
at org.inventivetalent.reflection.resolver.FieldResolver.<init>(FieldResolver.java:15) ~[?:?]
at org.inventivetalent.mapmanager.PacketListener.<clinit>(PacketListener.java:24) ~[?:?]
... 11 more
[17:23:43] [Server thread/INFO]: [MapManager] Disabling MapManager v1.8.3-SNAPSHOT
[17:23:43] [Server thread/ERROR]: Error occurred while disabling MapManager v1.8.3-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException:  Cannot invoke "org.inventivetalent.mapmanager.PacketListener.disable()"  because "this.packetListener" is null
at org.inventivetalent.mapmanager.MapManagerPlugin.onDisable(MapManagerPlugin.java:126) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"15e4b30"]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by OBattler** [comment]
Updated to the latest PacketListenerAPI, and still the same.

**Comment by stijnb1234** [comment]
Waiting on #69

**Comment by Thornbush42** [comment]
Can we get a build triggered?

**Comment by stijnb1234** [comment]
Tested with the update, but that's not enough to get 1.17 support working.

**Comment by stijnb1234** [comment]
@InventivetalentDev Any idea when 1.17 support for MapManager will be done?

**Comment by stijnb1234** [comment]
Building the latest versions of MapManager and PacketlistenerAPI fixed this issue, but now I get this console spam:

https://pastebin.com/gtHVYH1z
https://pastebin.com/GjMuTc5A

**Comment by stijnb1234** [comment]
@InventivetalentDev Any update?

**Comment by InventivetalentDev** [comment]
nope

**Comment by stijnb1234** [comment]
> nope

Do you have any ETA when this API will get an update to 1.17? I use it in my plugin.

**Comment by InventivetalentDev** [comment]
i do not. feel free to tinker with it yourself and submit a pr
