### ISSUE TITLE
1.18 support: ClassNotFoundException: Could not resolve class for net.minecraft.server.v1_18_R1.Entity

### ISSUE THREAD

**Issue by Dymeth** [InventivetalentDev/MapManager#81]
Paper version git-Paper-84 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: ae6fec6)
PacketListenerApi v3.9.9-SNAPSHOT
MapManager v1.8.5-SNAPSHOT

Looks like MapManager can't enable on Paper 1.18 due to packages location changed in NMS:

```21.12.21 13:17:04 > INFO > [MapManager] [STDOUT] [ReflectionHelper/MinecraftVersion] Version is v1_18_R1 (11801)
21.12.21 13:17:04 > ERROR > Error occurred while enabling MapManager v1.8.5-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.inventivetalent.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:21) ~[?:?]
	at org.inventivetalent.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:17) ~[?:?]
	at org.inventivetalent.mapmanager.PacketListener.<clinit>(PacketListener.java:26) ~[?:?]
	at org.inventivetalent.mapmanager.MapManagerPlugin.onEnable(MapManagerPlugin.java:70) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-84]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:507) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-84]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_18_R1.Entity', types=[]}, ResolverQuery{name='net.minecraft.server.v1_18_R1.Entity', types=[]}]
	at org.inventivetalent.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:55) ~[?:?]
	... 20 more
Caused by: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_18_R1.Entity', types=[]}, ResolverQuery{name='net.minecraft.server.v1_18_R1.Entity', types=[]}]
	at org.inventivetalent.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:42) ~[?:?]
	at org.inventivetalent.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:9) ~[?:?]
	at org.inventivetalent.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:63) ~[?:?]
	at org.inventivetalent.reflection.resolver.ClassResolver.resolve(ClassResolver.java:29) ~[?:?]
	at org.inventivetalent.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:28) ~[?:?]
	at org.inventivetalent.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:52) ~[?:?]
	... 20 more```

**Comment by Malhera** [comment]
Same issue. Meanwhile that plugin is necessary for [AnimatedFrames](https://github.com/InventivetalentDev/AnimatedFrames) to work, which is fluking pinned on InventivetalentDev github page!

**Comment by MishaOpstal** [comment]
I hope it won't be long until a new version releases for 1.18.x

**Comment by stijnb1234** [comment]
@InventivetalentDev Can you please look into this issue?

**Comment by ChrissW-R1** [comment]
It works with the latest version 1.8.6-SNAPSHOT (https://github.com/InventivetalentDev/MapManager/releases/tag/1.8.6-SNAPSHOT)
