### ISSUE TITLE
Frame Update Problem

### ISSUE THREAD

**Issue by Blubberboy7002** [InventivetalentDev/MapManager#84]
Whenever the plugin tries to reload the frames, this message pops up in the console:

[22:46:53 WARN]: [MapManager] Task #5453 for MapManager v1.8.6-SNAPSHOT generated an exception

1. Go to your server with MapManager and a plugin that uses it
2. Make it change a framepjes 

Expected:
the plugin reloads the frame and it updates

#

**Comment by stijnb1234** [comment]
Please include the full error.

**Comment by Blubberboy7002** [comment]
[11:02:09 WARN]: [MapManager] Task #7376 for MapManager v1.8.6-SNAPSHOT generated an exception
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "this.field" is null
        at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:447) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
        at org.inventivetalent.mapmanager.DefaultMapWrapper$1.lambda$showInFrame$0(DefaultMapWrapper.java:252) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-173]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-173]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-173]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-173]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-173]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-173]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-173]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "this.field" is null
        at org.inventivetalent.reflection.accessor.FieldAccessor.get(FieldAccessor.java:43) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
        at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:422) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
        ... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "this.field" is null
        at org.inventivetalent.reflection.accessor.FieldAccessor.get(FieldAccessor.java:41) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
        at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:422) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
        ... 9 more

**Comment by InventivetalentDev** [comment]
use the issue template.

**Comment by Blubberboy7002** [comment]
That’s what i did!

again:

Whenever the plugin tries to reload the frames, this message pops up in the console:

[11:02:09 WARN]: [MapManager] Task #7376 for MapManager v1.8.6-SNAPSHOT generated an exception
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "this.field" is null
at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:447) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
at org.inventivetalent.mapmanager.DefaultMapWrapper$1.lambda$showInFrame$0(DefaultMapWrapper.java:252) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-173]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-173]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-173]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-173]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-173]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-173]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-173]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "this.field" is null
at org.inventivetalent.reflection.accessor.FieldAccessor.get(FieldAccessor.java:43) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:422) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "this.field" is null
at org.inventivetalent.reflection.accessor.FieldAccessor.get(FieldAccessor.java:41) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:422) ~[MapManager_v1.8.6-SNAPSHOT.jar:?]
... 9 more

Steps to reproduce the behavior:

Go to your server with MapManager and a plugin that uses it
Make it change a framepjes
Expected:
the plugin reloads the frame and it updates

**Comment by stijnb1234** [comment]
> use the issue template.

Check the first message. I just asked for the full error.

**Comment by Blubberboy7002** [comment]
And how do you do that? Because this is all i get…

**Comment by stijnb1234** [comment]
> And how do you do that? Because this is all i get…

No, that quote was to @InventivetalentDev because your message was right.

**Comment by Blubberboy7002** [comment]
Ow, ok, sorry…
