### ISSUE TITLE
ClassCastException on 1.19

### ISSUE THREAD

**Issue by stijnb1234** [InventivetalentDev/MapManager#90]
**Describe the bug**
The plugin gives me an error on 1.19.

```
[11:11:12 WARN]: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class net.minecraft.world.phys.Vec3D cannot be cast to class java.lang.Double (net.minecraft.world.phys.Vec3D is in unnamed module of loader java.net.URLClassLoader @3b764bce; java.lang.Double is in module java.base of loader 'bootstrap')
[11:11:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftFuture.get(CraftFuture.java:73)
[11:11:12 WARN]:        at MapManager_v1.8.8-SNAPSHOT (1).jar//org.inventivetalent.mapmanager.PacketListener$1.onReceive(PacketListener.java:119)
[11:11:12 WARN]:        at PacketListenerAPI_v3.9.10-SNAPSHOT (1).jar//org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:108)
[11:11:12 WARN]:        at PacketListenerAPI_v3.9.10-SNAPSHOT (1).jar//org.inventivetalent.packetlistener.PacketListenerAPI.onPacketReceive(PacketListenerAPI.java:103)
[11:11:12 WARN]:        at PacketListenerAPI_v3.9.10-SNAPSHOT (1).jar//org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketReceive(ChannelAbstract.java:97)
[11:11:12 WARN]:        at PacketListenerAPI_v3.9.10-SNAPSHOT (1).jar//org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:139)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[11:11:12 WARN]:        at PacketListenerAPI_v3.9.10-SNAPSHOT (1).jar//org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:142)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at ProtocolLib (12).jar//com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[11:11:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[11:11:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[11:11:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[11:11:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[11:11:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:11:12 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:11:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:11:12 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:11:12 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[11:11:12 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[11:11:12 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[11:11:12 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[11:11:12 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[11:11:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[11:11:12 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:11:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:11:12 WARN]: Caused by: java.lang.ClassCastException: class net.minecraft.world.phys.Vec3D cannot be cast to class java.lang.Double (net.minecraft.world.phys.Vec3D is in unnamed module of loader java.net.URLClassLoader @3b764bce; java.lang.Double is in module java.base of loader 'bootstrap')
[11:11:12 WARN]:        at MapManager_v1.8.8-SNAPSHOT (1).jar//org.inventivetalent.mapmanager.PacketListener.vec3DtoVector(PacketListener.java:152)
[11:11:12 WARN]:        at MapManager_v1.8.8-SNAPSHOT (1).jar//org.inventivetalent.mapmanager.PacketListener$1.lambda$onReceive$0(PacketListener.java:111)
[11:11:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[11:11:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[11:11:12 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[11:11:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[11:11:12 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
[11:11:12 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
[11:11:12 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[11:11:12 WARN]:        ... 1 more
```

**To Reproduce**
1. Create an image with the API
2. See this error.

**Expected behavior**
It should give no errors.

**Comment by Woflje** [comment]
Hi @stijnb1234 , I have the same issue. Why did you close the issue? Did you find a solution?

**Comment by stijnb1234** [comment]
> Hi @stijnb1234 , I have the same issue. Why did you close the issue? Did you find a solution?

That's because I made my own fork instead.

**Comment by Woflje** [comment]
@stijnb1234 do you have that fork available somewhere? I don't see a fork within the last 16 days of a MapManager. Sorry I am really looking for this - in 2 days I am trying to have multiple MC Servers ready for a big LANparty ^-^

**Comment by Woflje** [comment]
I found your work 'MapReflectionAPI'! I cannot use it however, as the AnimatedFrames plugins requires MapManager and otherwise just does not start.
